### ISSUE TITLE
labels.csv does not exists

### ISSUE THREAD

**Issue by rezacsedu** [naveenrc/YelpChallenge#1]
Hi,

I have downloaded the Yelp dataset. However, there is no labels.csv file inside. Any suggestion?

**Comment by naveenrc** [comment]
Hi,
labels.csv is created when you run photo_process.py
It doesn`t come with yelp data.

**Comment by rezacsedu** [comment]
@naveenrc , thanks for responding. But sorry to bother you again! When I execute the photo_process.py script, I experience the following error:

`OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3483`

Could you please help me on that?

**Comment by naveenrc** [comment]
No problem, happy to solve the issues. Could you please post the complete error.

**Comment by naveenrc** [comment]
Hi, make sure you place the photos in yelpData/yelpPhotos directory. Pull the current changes. I have made a few modifications. Now it should run. Please let me know if you face any other issues.
